steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'flugarsuma', '--region', 'europe-west1', '--runtime', 'python310', '--source', '.', '--entry-point', 'storage_event', '--trigger-resource', 'projects/proj1miax/buckets/storagesuma12', '--trigger-event', 'google.storage.object.finalize', '--allow-unauthenticated']
