steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'fsumagit', '--region', 'europe-west1', '--runtime', 'python310', '--source', '.', '--entry-point', 'create_dict', '--trigger-http', '--allow-unauthenticated']
