steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'fstorage', '--region', 'europe-west1', '--runtime', 'python310', '--trigger-bucket', 'storagesuma12', '--entry-point', 'storage_event', '--allow-unauthenticated']

